---
        #RB ------------------------------------------------------------------------------------------------------------- RB#
        #RB ***** The Playbook first starts to check for any previously installed tools so it can decide on         ***** RB#
        #RB ***** reinstalling those tools or upgrading them later.                                                 ***** RB#
        #RB ------------------------------------------------------------------------------------------------------------- RB#
- name: "Install dependencies"
  package:
    name:
      - stunnel
    state: latest

- name: Create stunnel dir
  file: 
    path: /etc/stunnel/
    state: directory

- name: "Generate self-signed certificate for stunnel"
  shell: openssl req -newkey rsa:4096 -x509 -sha512 -days 365 -nodes -out certificate.pem -keyout privatekey.pem -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=localhost"
  args:
    chdir: /etc/stunnel/

- name: "Append key to cert file"
  shell: cat /etc/stunnel/certificate.pem > /etc/stunnel/full.pem && cat /etc/stunnel/privatekey.pem >> /etc/stunnel/full.pem

- name: "Copy Stunnel config file"
  template:
    src: stunnel.conf
    dest: /etc/stunnel/stunnel.conf
  notify: run stunnel

